### PR TITLE
srcANGULAR: bumped security patches

### PR DESCRIPTION
**Pull request by hollowaykeanho**
It appears there were still some security patches went out of order. Hence, let's update it.

This patch bumps security patches into srcANGULAR/ directory.

### CODE REVIEW

**Comment by hollowaykeanho** [comment]
left over patches from Goto project.

**Review by corygalyna — APPROVED** [review]
everything were automated. Skipped.

**Comment by hollowaykeanho** [comment]
thanks.

**Comment by corygalyna** [comment]
Can you do the merge? Thanks.

**Pull request merged**
